apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: docker.io/selat/consumer:1.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: 'service.name=consumer,service.namespace=ubisafe'
            - name: OTEL_METRICS_EXPORTER
              value: 'none'
            - name: AWS_ACCESS_KEY_ID
              value: ''
            - name: AWS_SECRET_ACCESS_KEY
              value: ''
        - name: aws-otel-collector
          image: amazon/aws-otel-collector:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              value: ''
            - name: AWS_SECRET_ACCESS_KEY
              value: ''
            - name: AWS_REGION
              value: 'us-east-1'
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 32m
              memory: 24Mi