receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681

processors:
  memory_limiter:
    limit_mib: 100
    check_interval: 5s

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: 'us-east-1'
    index_all_attributes: true

service:
  pipelines:
    traces:
      processors: [memory_limiter]
      receivers: [otlp]
      exporters: [awsxray]
